site_name: JavaGems3D

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API: api.md
  - Game Editor: editor.md
  - Graphics: graphics.md
  - Physics: physics.md
  - Sounds: sounds.md
  - Build Game: build-game.md