<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <properties>
        <github.global.server>github</github.global.server>
        <lwjgl.version>3.4.1</lwjgl.version>
        <joml.version>1.10.8</joml.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <imgui.artifactId>imgui-java-natives-windows</imgui.artifactId>
        <lwjgl.natives>natives-windows</lwjgl.natives>
        <bullet.artifactId>Libbulletjme-Windows64</bullet.artifactId>
        <bullet.version>22.0.3</bullet.version>
        <bullet.classifier>SpDebug</bullet.classifier>
    </properties>

    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.gltexture</groupId>
    <artifactId>javagems3d</artifactId>
    <version>beta0.1.1</version>
    <packaging>pom</packaging>

    <name>JavaGems3D</name>
    <description>3-D Java Game Engine</description>
    <url>https://github.com/gltexture/javagems3d</url>

    <modules>
        <module>syslogger</module>
        <module>engine</module>
        <module>launcher</module>
        <module>workbench</module>
    </modules>

    <scm>
        <url>https://github.com/gltexture/javagems3d</url>
        <connection>scm:git:git://github.com/gltexture/javagems3d.git</connection>
        <developerConnection>scm:git:ssh://github.com/gltexture/javagems3d.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>BSD-3-Clause license</name>
            <url>https://github.com/gltexture/javagems3d?tab=BSD-3-Clause-1-ov-file</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>gltexture</id>
        </developer>
    </developers>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub gltexture Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/gltexture/javagems3d</url>
        </repository>
    </distributionManagement>

    <profiles>
        <profile>
            <id>linux-x86_64</id>
            <activation>
                <os>
                    <family>unix</family>
                    <name>linux</name>
                    <arch>amd64</arch>
                </os>
            </activation>
            <properties>
                <lwjgl.natives>natives-linux</lwjgl.natives>
                <imgui.artifactId>imgui-java-natives-linux</imgui.artifactId>
                <bullet.artifactId>Libbulletjme-Linux64</bullet.artifactId>
            </properties>
        </profile>

        <profile>
            <id>linux-arm64</id>
            <activation>
                <os>
                    <family>unix</family>
                    <name>linux</name>
                    <arch>aarch64</arch>
                </os>
            </activation>
            <properties>
                <lwjgl.natives>natives-linux-arm64</lwjgl.natives>
                <imgui.artifactId>imgui-java-natives-arm64</imgui.artifactId>
                <bullet.artifactId>Libbulletjme-Linux_ARM64</bullet.artifactId>
            </properties>
        </profile>

        <profile>
            <id>windows</id>
            <activation>
                <os>
                    <family>windows</family>
                    <arch>amd64</arch>
                </os>
            </activation>
            <properties>
                <lwjgl.natives>natives-windows</lwjgl.natives>
                <imgui.artifactId>imgui-java-natives-windows</imgui.artifactId>
                <bullet.artifactId>Libbulletjme-Windows64</bullet.artifactId>
            </properties>
        </profile>

        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <lwjgl.natives>natives-macos</lwjgl.natives>
                <imgui.artifactId>imgui-java-natives-macos</imgui.artifactId>
            </properties>
        </profile>
    </profiles>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.gltexture</groupId>
                <artifactId>SysLogger</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gltexture</groupId>
                <artifactId>Engine</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gltexture</groupId>
                <artifactId>Launcher</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gltexture</groupId>
                <artifactId>DefaultApp</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.gltexture</groupId>
                <artifactId>Workbench</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.lwjgl</groupId>
                <artifactId>lwjgl-bom</artifactId>
                <version>${lwjgl.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.lmax</groupId>
            <artifactId>disruptor</artifactId>
            <version>3.4.4</version>
        </dependency>
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js</artifactId>
            <version>25.0.2</version>
            <type>pom</type>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.graalvm.js</groupId>
            <artifactId>js-scriptengine</artifactId>
            <version>25.0.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>nuprocess</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.10.2</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>2.2</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.11.0</version>
        </dependency>

        <dependency>
            <groupId>com.github.stephengold</groupId>
            <artifactId>Libbulletjme-Linux_ARM64</artifactId>
            <version>${bullet.version}</version>
            <classifier>${bullet.classifier}</classifier>
        </dependency>
        <dependency>
            <groupId>com.github.stephengold</groupId>
            <artifactId>Libbulletjme-Windows64</artifactId>
            <version>${bullet.version}</version>
            <classifier>${bullet.classifier}</classifier>
        </dependency>
        <dependency>
            <groupId>com.github.stephengold</groupId>
            <artifactId>Libbulletjme-Linux64</artifactId>
            <version>${bullet.version}</version>
            <classifier>${bullet.classifier}</classifier>
        </dependency>

        <dependency>
            <groupId>com.github.stephengold</groupId>
            <artifactId>${bullet.artifactId}</artifactId>
            <version>${bullet.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.spair</groupId>
            <artifactId>imgui-java-binding</artifactId>
            <version>1.86.11</version>
        </dependency>
        <dependency>
            <groupId>io.github.spair</groupId>
            <artifactId>${imgui.artifactId}</artifactId>
            <version>1.86.11</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.2.0-jre</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.2.12.Final</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.25.4</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.25.4</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-assimp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-bgfx</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-nanovg</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-nuklear</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-openal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opengl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-par</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-stb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-vulkan</artifactId>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-assimp</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-bgfx</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-glfw</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-nanovg</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-nuklear</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-openal</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-opengl</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-par</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl-stb</artifactId>
            <classifier>${lwjgl.natives}</classifier>
        </dependency>
        <dependency>
            <groupId>org.joml</groupId>
            <artifactId>joml</artifactId>
            <version>${joml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>24.1.0</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <id>sonatype-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>