layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) uniform sampler2D inputTexture;

layout(std430, binding = 8) buffer TextureScan {
    uint hasTransparency;
};

void main() {
    ivec2 texSize = textureSize(inputTexture, 0);
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

    if (uv.x >= texSize.x || uv.y >= texSize.y) return;

    float alpha = texelFetch(inputTexture, uv, 0).a;

    if (alpha > 0.0 && alpha < 1.0) {
        atomicOr(hasTransparency, 1);
    }
}
