package javagems3d.system.resources.assets.shaders.uniform;

public enum DefaultUniformDefinitions {
    PROJECTION_MODEL_MATRIX("projection_model_matrix"),
    PROJECTION_MATRIX("projection_matrix"),
    TEXTURE_MAP("texture_map"),
    BRIGHT_MAP("bright_map"),
    SCALE("scale"),
    COLOR("color"),
    MODEL_MATRIX("model_matrix"),
    VIEW_MATRIX("view_matrix"),
    CAMERA_MATRIX("camera_matrix"),
    USE_TEXTURE("use_texture"),
    CAMERA_POS("camera_pos"),
    INPUT_TEXTURE("inputTexture"),
    AMBIENT_CUBEMAP("ambient_cubemap"),
    SELECTED("selected"),
    USE_CUBE_MAP("useCubeMap"),
    W_TICK("w_tick"),
    PROJECTION_VIEW_MATRIX("projection_view_matrix"),
    BLUR("blur"),
    USE_FXAA("use_fxaa"),
    RESOLUTION("resolution"),
    DIRECTION("direction"),
    DRAW_CENTER_RECT("drawCenterRect"),
    SHOW_CASCADES("showCascades"),
    ALPHA_DISCARD("alpha_discard"),
    BLOOM_MAP1("bloom_map1"),
    BLOOM_MAP2("bloom_map2"),
    POS_EXP("PosExp"),
    NEG_EXP("NegExp"),
    G_POSITIONS("gPositions"),
    G_NORMALS("gNormals"),
    G_TEXTURE("gTexture"),
    G_EMISSION("gEmission"),
    G_METALLIC_ROUGHNESS("gMetallicRoughness"),
    TEXTURE_SCALING("texture_scaling"),
    BACKGROUND_COLOR("background_color"),
    SPOT_LIGHT_SHADOW_PROJECTION_VIEW("spot_light_shadow_projection_view_"),
    CASCADE_SHADOW_PROJECTION_VIEW("cascade_shadow_projection_view_"),
    CASCADE_SHADOW_SPLIT_DISTANCE("cascade_shadow_split_distance_"),
    ANIMATIONS_MATRIX("animations_matrix"),
    DIFFUSE_COLOR("diffuse_color"),
    SSAO_BIAS("ssao_bias"),
    SSAO_RADIUS("ssao_radius"),
    SSAO_RANGE("ssao_range"),
    SSAO_MAP("ssao_map"),
    SSAO_NOISE("ssaoNoise"),
    SSAO_KERNEL("ssaoKernel"),
    ACCUMULATED_ALPHA("accumulated_alpha"),
    POINT_LIGHT_FAR_PLANE("pl_far_plane"),
    SPOT_LIGHT_FAR_PLANE("sl_far_plane"),
    REVEAL_ALPHA("reveal_alpha"),
    SKYBOX_CUBE("skybox_cube"),
    FXAA_SPAN_MAX("FXAA_SPAN_MAX"),
    SKYBOX_BACKGROUND("skybox_background"),
    DIFFUSE_MAP("diffuse_map"),
    LIGHT_POS("lightPos"),
    LIGHT("light"),
    IS_SSAO_VALID("isSsaoValid"),
    EXPOSURE("exposure"),
    GAMMA("gamma"),
    USE_HDR("use_hdr"),
    BLOOM_MAP("bloom_map"),
    VIEW_SCALING("view_scaling"),
    NOISE_SCALE("noiseScale"),
    COVERED_BY_FOG("covered_by_fog"),
    VIEW("view"),
    VIEW_MAT_INVERTED("view_mat_inverted"),
    MODEL_VIEW_MATRIX("model_view_matrix"),
    DRAW_SUN_MULT("draw_sun_mult"),
    SKYBOX_FACE_2D("skybox_face2D"),
    SKYBOX_FACE_HINT("skybox_faceHint"),
    DO_HINT("doHint"),
    OPACITY("opacity"),
    EMISSION_COLOR("emission_color"),
    METALLIC_FACTOR("metallic_factor"),
    ROUGHNESS_FACTOR("roughness_factor"),
    EMISSION_MAP("emission_map"),
    NORMALS_MAP("normals_map"),
    METALLIC_ROUGHNESS_MAP("metallicRoughnessMap"),
    TEXTURING_CODE("texturing_code"),
    SUN_SHADOW_MAP("sun_shadow_map_"),
    POINT_LIGHT_CUBE_MAP("point_light_cubemap_"),
    SPOT_LIGHT_SHADOW_MAP("spot_light_shadow_map_");

    private final String s;

    DefaultUniformDefinitions(String s) {
        this.s = s;
    }

    public String getS() {
        return this.s;
    }
}
